"""
regenerate_model_weights_h.py
把训练后的 model_weights.pth 重新生成 model_weights.h
（解决"训练后没重新编译固件 → MCU 用旧 SE 权重"的问题）

用法：
    python regenerate_model_weights_h.py
    python regenerate_model_weights_h.py --input path/to/model_weights.pth
    python regenerate_model_weights_h.py --cfg path/to/model_config.json --output D:/15/Core/Inc
"""
import os
import sys
import json
import argparse
import numpy as np

def main():
    parser = argparse.ArgumentParser(description="重新生成 model_weights.h (C 头文件)")
    parser.add_argument('--input', default=r'D:\15\ai_training\projects\1\model1\weights\model_weights.pth',
                        help='训练后的 .pth 权重路径')
    parser.add_argument('--cfg', default=r'D:\15\ai_training\projects\1\model1\evaluation\model_config.json',
                        help='model_config.json 路径')
    parser.add_argument('--output', default=r'D:\15\Core\Inc',
                        help='model_weights.h 输出目录')
    parser.add_argument('--quantize', action='store_true', default=False,
                        help='同时生成 model_weights_q.h (INT8 量化)')
    args = parser.parse_args()

    import torch
    print(f'[*] 加载权重: {args.input}')
    state = torch.load(args.input, map_location='cpu')
    print(f'[*] 加载配置: {args.cfg}')
    with open(args.cfg, 'r', encoding='utf-8') as f:
        cfg = json.load(f)

    nc = cfg['num_classes']
    cn = cfg['class_names']
    cc = cfg.get('class_to_cmd', [0] * nc)
    has_se = bool(cfg.get('has_se', True))
    se_reduction = int(cfg.get('se_reduction', 4))
    se1_hidden = 48 // se_reduction if has_se else 0
    se2_hidden = 64 // se_reduction if has_se else 0
    conf_threshold = float(cfg.get('conf_threshold', 0.7))
    margin_threshold = float(cfg.get('margin_threshold', 0.2))
    noise_index = int(cfg.get('noise_index', -1))

    print(f'[*] num_classes={nc}  has_se={has_se}  se_red={se_reduction}')
    print(f'[*] conf_threshold={conf_threshold:.3f}  margin_threshold={margin_threshold:.3f}  noise_index={noise_index}')
    print(f'[*] class_names={cn}')

    os.makedirs(args.output, exist_ok=True)
    out_path = os.path.join(args.output, 'model_weights.h')

    all_params = {}
    for name, tensor in state.items():
        all_params[name] = tensor.numpy()

    # 写 model_weights.h (Float32)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('#ifndef MODEL_WEIGHTS_H\n#define MODEL_WEIGHTS_H\n\n')
        f.write('/* Auto-generated by regenerate_model_weights_h.py */\n')
        f.write('/* DS-CNN + SE Float32 Weights */\n\n')
        f.write(f'#define NUM_CLASSES     {nc}\n')
        f.write('#define FRAME_WINDOW    32\n')
        f.write('#define MEL_NUM_FILTERS  20\n')
        f.write('#define CONV1_OUT       32\n')
        f.write('#define CONV2_OUT       48\n')
        f.write('#define CONV3_OUT       64\n')
        f.write('#define POOL1_LEN       (FRAME_WINDOW / 2)\n')
        f.write('#define POOL2_LEN       (FRAME_WINDOW / 4)\n')
        f.write(f'#define HAS_SE          {1 if has_se else 0}\n')
        f.write(f'#define SE_REDUCTION    {se_reduction}\n')
        f.write(f'#define SE1_HIDDEN      {se1_hidden}\n')
        f.write(f'#define SE2_HIDDEN      {se2_hidden}\n')
        f.write(f'#define CONF_THRESHOLD  {conf_threshold:.4f}f\n')
        f.write(f'#define MARGIN_THRESHOLD {margin_threshold:.4f}f\n')
        f.write(f'#define NOISE_INDEX     {noise_index}\n\n')
        f.write('static const char* class_labels[NUM_CLASSES] = {\n')
        for name in cn:
            f.write(f'    "{name}",\n')
        f.write('};\n\n')
        f.write('static const char* class_display[NUM_CLASSES] = {\n')
        for name in cn:
            f.write(f'    "{name}",\n')
        f.write('};\n\n')
        f.write(f"static const int class_to_cmd[NUM_CLASSES] = {{{', '.join(str(v) for v in cc)}}};\n\n")
        for name, arr in all_params.items():
            data = arr.flatten()
            safe = name.replace('.', '_')
            f.write(f'static const float {safe}[{len(data)}] = {{\n')
            for i in range(0, len(data), 8):
                line = ', '.join(f'{float(v):12.8f}f' for v in data[i:i+8])
                f.write(f'    {line},\n')
            f.write('};\n\n')
        f.write('#endif\n')
    print(f'[OK] 已生成: {out_path} ({os.path.getsize(out_path)} bytes)')

    if args.quantize:
        out_q_path = os.path.join(args.output, 'model_weights_q.h')
        quant_names = ['depth1.weight', 'point1.weight',
                       'depth2.weight', 'point2.weight', 'fc.weight']
        if has_se:
            quant_names += ['se1.fc1.weight', 'se1.fc2.weight',
                            'se2.fc1.weight', 'se2.fc2.weight']
        with open(out_q_path, 'w', encoding='utf-8') as f:
            f.write('#ifndef MODEL_WEIGHTS_Q_H\n#define MODEL_WEIGHTS_Q_H\n\n')
            f.write('/* Auto-generated by regenerate_model_weights_h.py */\n')
            f.write('/* DS-CNN + SE INT8 Quantized Weights */\n\n')
            f.write(f'#define NUM_CLASSES     {nc}\n')
            f.write('#define FRAME_WINDOW    32\n')
            f.write('#define MEL_NUM_FILTERS  20\n')
            f.write('#define CONV1_OUT       32\n')
            f.write('#define CONV2_OUT       48\n')
            f.write('#define CONV3_OUT       64\n')
            f.write('#define POOL1_LEN       (FRAME_WINDOW / 2)\n')
            f.write('#define POOL2_LEN       (FRAME_WINDOW / 4)\n')
            f.write(f'#define HAS_SE          {1 if has_se else 0}\n')
            f.write(f'#define SE_REDUCTION    {se_reduction}\n')
            f.write(f'#define SE1_HIDDEN      {se1_hidden}\n')
            f.write(f'#define SE2_HIDDEN      {se2_hidden}\n')
            f.write(f'#define CONF_THRESHOLD  {conf_threshold:.4f}f\n')
            f.write(f'#define MARGIN_THRESHOLD {margin_threshold:.4f}f\n')
            f.write(f'#define NOISE_INDEX     {noise_index}\n\n')
            f.write('static const char* class_labels[NUM_CLASSES] = {\n')
            for name in cn:
                f.write(f'    "{name}",\n')
            f.write('};\n\n')
            f.write('static const char* class_display[NUM_CLASSES] = {\n')
            for name in cn:
                f.write(f'    "{name}",\n')
            f.write('};\n\n')
            f.write(f"static const int class_to_cmd[NUM_CLASSES] = {{{', '.join(str(v) for v in cc)}}};\n\n")
            for qname in quant_names:
                if qname in all_params:
                    arr = all_params[qname]
                    abs_max = np.max(np.abs(arr))
                    scale = abs_max / 127.0 if abs_max > 0 else 1.0/127.0
                    q = np.round(arr/scale).clip(-128,127).astype(np.int8)
                    safe = qname.replace('.', '_')
                    f.write(f'static const int8_t {safe}_q[{len(q.flatten())}] = {{\n')
                    for i in range(0, len(q.flatten()), 16):
                        line = ','.join(f'{int(v):4d}' for v in q.flatten()[i:i+16])
                        f.write(f'    {line},\n')
                    f.write('};\n\n')
                    f.write(f'static const float {safe}_scale = {scale:.8f}f;\n\n')
            for name, arr in all_params.items():
                if name in quant_names:
                    continue
                data = arr.flatten()
                safe = name.replace('.', '_')
                f.write(f'static const float {safe}[{len(data)}] = {{\n')
                for i in range(0, len(data), 8):
                    line = ', '.join(f'{float(v):12.8f}f' for v in data[i:i+8])
                    f.write(f'    {line},\n')
                f.write('};\n\n')
            f.write('#endif\n')
        print(f'[OK] 已生成: {out_q_path} ({os.path.getsize(out_q_path)} bytes)')

    print('\n[!] 重要：生成后必须重新编译 MCU 固件，新权重才生效！')
    print('[!] 编译命令（Keil）: Project → Rebuild All → Download to Flash')

if __name__ == '__main__':
    main()
